### ISSUE TITLE
NameError: name 'ffpython' is not defined

### ISSUE THREAD

**Issue by souryuu** [fanchy/ffpython#10]
Thank you for the code. I got the following error when trying to embed python script in C++.

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemError: nameless module
Traceback (most recent call last):
  File "<string>", line 8, in <module>
NameError: name 'ffpython' is not defined
Traceback (most recent call last):
  File "<string>", line 11, in <module>
NameError: name 'ffpython' is not defined
Traceback (most recent call last):
  File "<string>", line 10, in <module>
NameError: name 'ffpython' is not defined
Traceback (most recent call last):
  File "<string>", line 6, in <module>
NameError: name 'ffpython' is not defined
sys.version=
ValueError: Empty module name

Here is the code Im running

```
std::shared_ptr<ff::FFPython> _ffpython;
_ffpython = std::make_shared<ff::FFPython>();
printf("sys.version=%s\n", _ffpython->getVar<std::string>("sys", "version").c_str());
```

 This run fine in python2.7, however, the error appeared when I switched to python3.5

**Comment by fanchy** [comment]
fixed, checkout new code
